CREATE TABLE IF NOT EXISTS USERS
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(100),
    birthday DATE CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    user_id BIGINT NOT NULL ,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friends_user FOREIGN KEY(user_id) REFERENCES USERS(id) ON DELETE CASCADE ,
    CONSTRAINT fk_friends_friend FOREIGN KEY(friend_id) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT chk_friends_not_self CHECK (user_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS mpa_ratings
(
    mpa_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    mpa_name VARCHAR(255) NOT NULL UNIQUE ,
    PRIMARY KEY (mpa_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    genre_name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (genre_id)
);

CREATE TABLE IF NOT EXISTS FILMS
(
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    film_name VARCHAR(255) NOT NULL,
    film_description VARCHAR(255),
    film_release_date DATE CHECK (film_release_date >= DATE '1985-12-28'),
    film_duration INTEGER,
    film_mpa_rating_id INTEGER,
    PRIMARY KEY (film_id),
    CONSTRAINT fk_films_mpa_rating FOREIGN KEY (film_mpa_rating_id) REFERENCES mpa_rating(mpa_id)
);

CREATE TABLE IF NOT EXISTS FILM_GENRES
(
    film_id BIGINT,
    genre_id BIGINT,
    PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genres_film FOREIGN KEY (film_id) REFERENCES films(film_id) ON DELETE CASCADE ,
    CONSTRAINT fk_film_genres_genre FOREIGN KEY (genre_id) REFERENCES genres(genre_id) ON DELETE CASCADE
)



